workflows:
  default:
    name: Default Workflow
    environment:
      flutter: stable
    scripts:
      - name: Create .env file
        script: echo "WEATHER_API_KEY=$WEATHER_API_KEY" > .env
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
