workflows:
  default:
    name: Default Workflow
    environment:
      flutter: stable
    triggers:
      # Trigger the build only for the specified branch on push
      branches:
        only:
          - Weather-Testing-and-Welcome-Screen
    scripts:
      - name: Create .env file
        script: echo "WEATHER_API_KEY=$API_KEY" > .env
      - name: Print .env file
        script: cat .env
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
