workflows:
  default:
    name: Default Workflow
    environment:
      flutter: stable
    triggers:
      branches:
        only:
          - Weather-Testing-and-Welcome-Screen
    scripts:
      - name: Create .env file
        script: echo "WEATHER_API_KEY=$API_KEY" > .env
      - name: Print .env file
        script: cat .env
      - name: Install dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test

  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: 14.2
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install --project-directory=ios
      - name: Build for Simulator
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -configuration Debug -archivePath $HOME/runner/archives/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/runner/archives/Runner.xcarchive -exportPath $HOME/runner/exports -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - $HOME/runner/exports/*.ipa
